### ISSUE TITLE
Errors installing happybase package with https://github.com/pypa/distutils/commit/3e9d47

### ISSUE THREAD

**Issue by gunjan92604** [pypa/distutils#193]
[This commit](https://github.com/pypa/distutils/commit/3e9d47e) is throwing the following error when this version of distutils is used with happybase in a project built with python3.8. 

Trace from setup log:

```
Collecting happybase
  Downloading https://****/happybase-1.2.0.tar.gz (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 12.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /usr/local/lib/python3.8/dist-packages/setuptools/dist.py:770: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3t0d27xd/happybase_dd06a12d11eb4cd7a2db08a491f15e44/setup.py", line 23, in <module>
          setup(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 258, in __init__
          getattr(self.metadata, "set_" + key)(val)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 1242, in set_classifiers
          self.classifiers = _ensure_list(value, 'classifiers')
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 48, in _ensure_list
          log.warning(msg)
      AttributeError: module 'distutils.log' has no attribute 'warning'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by jaraco** [comment]
This was fixed in pypa/setuptools#3707 and Setuptools 65.6.3:

```
 draft $ pip-run setuptools -- -m pip install --no-build-isolation happybase
Collecting setuptools
  Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
Successfully installed setuptools-65.6.3
Collecting happybase
  Downloading happybase-1.2.0.tar.gz (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting thriftpy2>=0.4
  Downloading thriftpy2-0.4.16.tar.gz (643 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 643.4/643.4 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting ply<4.0,>=3.4
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 6.1 MB/s eta 0:00:00
Installing collected packages: ply, six, thriftpy2, happybase
  DEPRECATION: thriftpy2 is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for thriftpy2 ... done
  DEPRECATION: happybase is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for happybase ... done
Successfully installed happybase-1.2.0 ply-3.11 six-1.16.0 thriftpy2-0.4.16
```
