### ISSUE TITLE
LooseVersion: TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by hexcowboy** [pypa/distutils#22]
Considering the following:

```python
from distutils.version import LooseVersion

versions = ['2.2.9', '2.2a1', '2.2b1', '2.2rc1', '3.0']
versions = sorted(versions, key=LooseVersion)
versions = versions.sort(key=LooseVersion)         # This is redundant but both show the same error
```

The resulting error is thrown:
```
Traceback (most recent call last):
  File "/Users/jack/repos/djan/test/main.py", line 25, in <module>
    print(get_django_versions())
  File "/Users/jack/repos/djan/test/main.py", line 21, in get_django_versions
    versions = sorted(versions, key=LooseVersion)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/version.py", line 341, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

Versioning system used is [PEP386](https://www.python.org/dev/peps/pep-0386/).
Python version 3.9.1

**Comment by jaraco** [comment]
Distutils.version is deprecated. Use [packaging.version](https://packaging.pypa.io/en/latest/version.html#version-handling) instead. I'll clarify this with a proper deprecation warning.

**Comment by jaraco** [comment]
See #75
