### ISSUE TITLE
Support openSUSE specific behaviors

### ISSUE THREAD

**Issue by hswong3i** [pypa/distutils#85]
### setuptools version

60.0.3

### Python version

Python 3.8

### OS

openSUSE Tumbleweed

### Additional environment information

During RPM packaging.

### Description

I am packaging setuptools 60.0.3 with OBS (https://build.opensuse.org/package/show/home:alvistack/pypa-setuptools-60.0.3) for multiple OS deb/rpm.

It is only failed for openSUSE Tumbleweed during rpm packaging (https://build.opensuse.org/package/live_build_log/home:alvistack/pypa-setuptools-60.0.3/openSUSE_Tumbleweed/x86_64).

`platsubdir` is coming from an additional patch for openSUSE Factory Python 3.8: https://build.opensuse.org/package/view_file/openSUSE:Factory/python38/SUSE-FEDORA-multilib.patch

Also see https://bugzilla.opensuse.org/show_bug.cgi?id=1193977

P.S. my changes for deb/rpm packaging: https://github.com/alvistack/pypa-setuptools/commit/f73b5bc384148a9fffd51c7ef1d5463c14555537

### Expected behavior

Following OS build are successful:
* Fedora Rawhide (https://build.opensuse.org/package/live_build_log/home:alvistack/pypa-setuptools-60.0.3/Fedora_Rawhide/x86_64)
* Debian Testing (https://build.opensuse.org/package/live_build_log/home:alvistack/pypa-setuptools-60.0.3/Debian_Testing/x86_64)

### How to Reproduce
With `python3 setup.py install --skip-build` we FAILED:
```
sudo podman run -ti --rm opensuse/tumbleweed bash
zypper update
zypper install -y git curl wget python3 python3-devel python3-pip python3-setuptools python3-wheel
git clone https://github.com/pypa/setuptools.git
cd setuptools
git checkout v60.0.3
python3 setup.py build
python3 setup.py install --skip-build
```

With `pip install .` we PASS:
```
sudo podman run -ti --rm opensuse/tumbleweed bash
zypper update
zypper install -y git curl wget python3 python3-devel python3-pip python3-setuptools python3-wheel
git clone https://github.com/pypa/setuptools.git
cd setuptools
git checkout v60.0.3
python3 setup.py build
pip install .
```

### Output

Full log (https://build.opensuse.org/build/home:alvistack/openSUSE_Tumbleweed/x86_64/pypa-setuptools-60.0.3/_log):
```
[   22s] + /usr/bin/python3 setup.py install -O1 --skip-build --force --root /home/abuild/rpmbuild/BUILDROOT/python-setuptools-60.0.3-3.1.x86_64 --prefix /usr
[   23s] running install
[   23s] /home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
[   23s]   warnings.warn(
[   23s] Traceback (most recent call last):
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/util.py", line 258, in subst_vars
[   23s]     return _subst_compat(s).format_map(lookup)
[   23s] KeyError: 'platsubdir'
[   23s] 
[   23s] During handling of the above exception, another exception occurred:
[   23s] 
[   23s] Traceback (most recent call last):
[   23s]   File "setup.py", line 87, in <module>
[   23s]     dist = setuptools.setup(**setup_params)
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/__init__.py", line 153, in setup
[   23s]     return distutils.core.setup(**attrs)
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/core.py", line 148, in setup
[   23s]     return run_commands(dist)
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/core.py", line 163, in run_commands
[   23s]     dist.run_commands()
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/dist.py", line 967, in run_commands
[   23s]     self.run_command(cmd)
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/dist.py", line 985, in run_command
[   23s]     cmd_obj.ensure_finalized()
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
[   23s]     self.finalize_options()
[   23s]   File "setup.py", line 66, in finalize_options
[   23s]     install.finalize_options(self)
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/command/install.py", line 45, in finalize_options
[   23s]     orig.install.finalize_options(self)
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/command/install.py", line 422, in finalize_options
[   23s]     self.expand_dirs()
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/command/install.py", line 582, in expand_dirs
[   23s]     self._expand_attrs(['install_purelib', 'install_platlib',
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/command/install.py", line 572, in _expand_attrs
[   23s]     val = subst_vars(val, self.config_vars)
[   23s]   File "/home/abuild/rpmbuild/BUILD/python-setuptools_60.0.3-3.1/setuptools/_distutils/util.py", line 260, in subst_vars
[   23s]     raise ValueError(f"invalid variable {var}")
[   23s] ValueError: invalid variable 'platsubdir'
[   23s] error: Bad exit status from /var/tmp/rpm-tmp.qnWuVC (%install)
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hswong3i** [comment]
> In https://github.com/pypa/distutils/milestone/1, I've been tracking the various platforms' patches of distutils and supporting them. This issue appears to be another such patch. I'll move this issue to distutils as we continue investigation.
> 
> Thanks for the repro, I can confirm that the recommended opt-out for distutils is to set `SETUPTOOLS_USE_DISTUTILS=stdlib`, which does work around the reported issue.

With `SETUPTOOLS_USE_DISTUTILS=stdlib python3 setup.py install --skip-build` we PASS:
```
sudo podman run -ti --rm opensuse/tumbleweed bash
zypper update
zypper install -y git curl wget python3 python3-devel python3-pip python3-setuptools python3-wheel
git clone https://github.com/pypa/setuptools.git
cd setuptools
git checkout v60.0.3
python3 setup.py build
SETUPTOOLS_USE_DISTUTILS=stdlib python3 setup.py install --skip-build
```

P.S. this is so annoying for deb/rpm packaging, which 60.0.0+ enforcing me to add `SETUPTOOLS_USE_DISTUTILS=stdlib` for all build script manually...

**Comment by jaraco** [comment]
Running with this dockerfile proves the above patch is working:

```
from opensuse/tumbleweed
RUN zypper update
RUN zypper install -y git curl wget python3 python3-devel python3-pip python3-setuptools python3-wheel
RUN git clone https://github.com/pypa/setuptools.git
WORKDIR setuptools
RUN git config --global user.email "nobody@example.com"
RUN git config --global user.name "Nobody"
RUN git pull --no-rebase https://github.com/pypa/distutils.git
RUN python3 setup.py build
RUN python3 setup.py install --skip-build
```

**Comment by jaraco** [comment]
I note that although the install succeeds, there may still be other aspects of the patch that need to be addressed. For example, on Fedora, a patch to sysconfig needs to be added to set `_prefix_addition`. See some of the other issues in this milestone for various efforts to provide hooks to customize behavior.

**Comment by jaraco** [comment]
Oh, I should mention too that the install locations need to be customized in sysconfig (if they're not already).

**Comment by jaraco** [comment]
Confirmed that the install locations are already updated:

```
$ docker run -it @$(docker build -q .) python3 -c "import sysconfig; print(sysconfig._INSTALL_SCHEMES['posix_prefix']['platlib']); print(sysconfig._INSTALL_SCHEMES['posix_home']['platlib'])"
{platbase}/{platsubdir}/python{py_version_short}/site-packages
{base}/lib/python
```

**Comment by asottile** [comment]
this broke the tests, and presumably some functionality:

```console
$ pytest distutils/ -k 'test_user_site and test_install' --tb=native
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /tmp/distutils, configfile: pytest.ini
collected 296 items / 295 deselected / 1 selected                              

distutils/tests/test_install.py F                                        [100%]

=================================== FAILURES ===================================
________________________ InstallTestCase.test_user_site ________________________
Traceback (most recent call last):
  File "/tmp/distutils/distutils/tests/test_install.py", line 116, in test_user_site
    cmd.ensure_finalized()
  File "/tmp/distutils/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/distutils/distutils/command/install.py", line 429, in finalize_options
    self.create_home_path()
  File "/tmp/distutils/distutils/command/install.py", line 639, in create_home_path
    if path.startswith(home) and not os.path.isdir(path):
AttributeError: 'NoneType' object has no attribute 'startswith'
=========================== short test summary info ============================
FAILED distutils/tests/test_install.py::InstallTestCase::test_user_site - Att...
====================== 1 failed, 295 deselected in 0.38s =======================
```

**Comment by asottile** [comment]
yep this broke user installs:

```console
$ docker run --rm -ti ubuntu:focal bash -euxc 'apt-get update -qq >& /dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-distutils ca-certificates curl >& /dev/null && curl --location --silent https://bootstrap.pypa.io/get-pip.py | python3 - && pip install setuptools --upgrade && pip install --user astpretty --no-binary :all:'
+ apt-get update -qq
+ DEBIAN_FRONTEND=noninteractive
+ apt-get install -y --no-install-recommends python3 python3-distutils ca-certificates curl
+ curl --location --silent https://bootstrap.pypa.io/get-pip.py
+ python3 -
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 4.3 MB/s            
Collecting setuptools
  Downloading setuptools-60.0.4-py3-none-any.whl (952 kB)
     |████████████████████████████████| 952 kB 17.0 MB/s            
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-21.3.1 setuptools-60.0.4 wheel-0.37.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pip install setuptools --upgrade
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (60.0.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pip install --user astpretty --no-binary :all:
Collecting astpretty
  Downloading astpretty-2.1.0.tar.gz (5.4 kB)
  Preparing metadata (setup.py) ... done
Skipping wheel build for astpretty, due to binaries being disabled for it.
Installing collected packages: astpretty
    Running setup.py install for astpretty ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xjd_2vnp/astpretty_165bf4578d4043dea2cf66e37deae34b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xjd_2vnp/astpretty_165bf4578d4043dea2cf66e37deae34b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rmldmhyz/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /root/.local/include/python3.8/astpretty
         cwd: /tmp/pip-install-xjd_2vnp/astpretty_165bf4578d4043dea2cf66e37deae34b/
    Complete output (26 lines):
    running install
    /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xjd_2vnp/astpretty_165bf4578d4043dea2cf66e37deae34b/setup.py", line 2, in <module>
        setup()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 45, in finalize_options
        orig.install.finalize_options(self)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/install.py", line 429, in finalize_options
        self.create_home_path()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/install.py", line 639, in create_home_path
        if path.startswith(home) and not os.path.isdir(path):
    AttributeError: 'NoneType' object has no attribute 'startswith'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xjd_2vnp/astpretty_165bf4578d4043dea2cf66e37deae34b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xjd_2vnp/astpretty_165bf4578d4043dea2cf66e37deae34b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rmldmhyz/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /root/.local/include/python3.8/astpretty Check the logs for full command output.
```
