### ISSUE TITLE
--user installs broken with setuptools 60.0.4

### ISSUE THREAD

**Issue by asottile** [pypa/distutils#86]
see reproduction in https://github.com/pypa/distutils/issues/85#issuecomment-999916730

broken by this patch: https://github.com/pypa/distutils/commit/eba2bcd310caa49b51aa640055e44ef8c74b5581

**Comment by jaraco** [comment]
The test suite did test that `getconfigvar('platsubdir')` would reliably resolve to a string or None. What neither the Setuptools suite nor the Distutils suite tested was that a `None` value would be expected to have string interfaces (and not simply have a string representation).

**Comment by jaraco** [comment]
Traceback is:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xjd_2vnp/astpretty_165bf4578d4043dea2cf66e37deae34b/setup.py", line 2, in <module>
        setup()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 45, in finalize_options
        orig.install.finalize_options(self)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/install.py", line 429, in finalize_options
        self.create_home_path()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/install.py", line 639, in create_home_path
        if path.startswith(home) and not os.path.isdir(path):
    AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by asottile** [comment]
@jaraco the thing is [the testsuite *did* fail](https://github.com/pypa/distutils/issues/85#issuecomment-999913095), but it was pushed directly to `main` and ignored

**Comment by jaraco** [comment]
Yep. My mistake. Acknowledged in #90. Long term, the solution will be for these tests to be part of the Setuptools test suite and part of the integrated release process.
